### ISSUE TITLE
Program breaks while trying to execute an action without a loaded dataset

### ISSUE THREAD

**Issue by avilchess** [shapelets/al-juarismi#11]
**Describe the bug**
Aljuarismo breaks when trying to execute an action that requires a dataset and it hasn´t been loaded previously. We must check that condition and request a load of a dataset before the execution progress.

**To Reproduce**
```
: execute  kmeans
DEBUG: kmeans
Session path: projects/aljuaritmo/agent/sessions/cQvRW2O8PcAlIVdp3cZixUZZgi5NZAo7

{'number': '', 'Dataset': '', 'operation': 'kmeans'}
====================
Traceback (most recent call last):
DEBUG: Query text: kmeans
DEBUG: Detected intent: DoClustering (confidence: 0.4950000047683716)

  File "/Users/antonio.vilches/repositories/al-juarismi/main.py", line 107, in <module>
    main()
  File "/Users/antonio.vilches/repositories/al-juarismi/main.py", line 100, in main
    detect_intent_text(project_id, session_id, query, language_code)
  File "/Users/antonio.vilches/repositories/al-juarismi/main.py", line 79, in detect_intent_text
    al.do_clustering(parameters, current_dataset)
  File "/Users/antonio.vilches/repositories/al-juarismi/aljuarismi/operations.py", line 43, in do_clustering
    (centroids, labels) = al.kmean(dataset.values, parameters)
AttributeError: 'NoneType' object has no attribute 'values'
```
**Expected behavior**
It has to check the existence of a loaded dataset and pass this dataset to the execution command. If there is not a loaded dataset, it has to request the dataset to be loaded before progressing with the execution of the command.

**Desktop (please complete the following information):**
 - OS: MacOs 10.14

**Comment by Ocnarf2070** [comment]
Closing this issue. It is resolved in [PR12](https://github.com/shapelets/al-juarismi/pull/12)
