### ISSUE TITLE
Aljuarismi breaks while loading a dataset

### ISSUE THREAD

**Issue by avilchess** [shapelets/al-juarismi#7]
**Describe the bug**
If the user introduces an invalid path, the program breaks
**To Reproduce**

: load titanic2
Where is it located?
: /njkdnslanfgsaf/sadjndfhks

**Expected behavior**
The program informs the introduced path is invalid or it doesn´t exist

**Desktop (please complete the following information):**
 - OS: MacOS 
- 10.14

**Comment by Ocnarf2070** [comment]
This has been solved in [PR13](https://github.com/shapelets/al-juarismi/pull/13)
